server:
    port: 8082
spring:
    application:
        name: notification-service
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

notification:
    rabbitmq:
        exchange: notification.exchange
        queue: notification.queue
        routingkey: notification.routingkey


eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

    instance:
        hostname: localhost